### ISSUE TITLE
after installing TabNine for Vim using Vundle Vim fails to start

### ISSUE THREAD

**Issue by amircodota** [codota/tabnine-vim#55]
after installing TabNine for Vim using Vundle Vim fails to start with the following error:

Vim: Caught deadly signal ABRT
                              Error detected while processing function <SNR>57_OnVimLeave:Vim: Finished.

line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vasler/.vim/bundle/tabnine-vim/autoload/../python/ycm/youcompleteme.py", line 479, in OnVimLeave
    self._ShutdownServer()
  File "/home/vasler/.vim/bundle/tabnine-vim/autoload/../python/ycm/youcompleteme.py", line 282, in _ShutdownServer
    SendShutdownRequest()
  File "/home/vasler/.vim/bundle/tabnine-vim/autoload/../python/ycm/client/shutdown_request.py", line 45, in SendShutdownRequest
    request.Start()
  File "/home/vasler/.vim/bundle/tabnine-vim/autoload/../python/ycm/client/shutdown_request.py", line 39, in Start
    display_message = False )
  File "/home/vasler/.vim/bundle/tabnine-vim/autoload/../python/ycm/client/base_request.py", line 127, in PostDataToHandler
    BaseRequest.PostDataToHandlerAsync( data, handler, timeout ),
  File "/home/vasler/.vim/bundle/tabnine-vim/autoload/../python/ycm/client/base_request.py", line 137, in PostDataToHandlerAsync
    return BaseRequest._TalkToHandlerAsync( data, handler, 'POST', timeout )
  File "/home/vasler/.vim/bundle/tabnine-vim/autoload/../python/ycm/client/base_request.py", line 152, in _TalkToHandlerAsync
    return BaseRequest.Session().post(
  File "/home/vasler/.vim/bundle/tabnine-vim/autoload/../python/ycm/client/base_request.py", line 196, in Session
    from requests_futures.sessions import FuturesSession
ImportError: cannot import name FuturesSession
Aborted (core dumped)

OS: openSUSE Tumbleweed

**Comment by Shougo** [comment]
I think YCM API was changed.
