### ISSUE TITLE
get error message when press :<c-f> in vim

### ISSUE THREAD

**Issue by Lgggg** [codota/tabnine-vim#61]
I press : for commmand mode and then I press <c-f> for editting the command line in vim mode, but  i got err message like this:

处理 function <SNR>105_UpdateMatches 时发生错误:
第    1 行:
Traceback (most recent call last):
  File "/data/mm64/jiuluncai/lgenv/.vim/bundle/tabnine-vim/autoload/../python/ycm/vimsupport.py", line 1241, in CurrentWindow
    yield
  File "/data/mm64/jiuluncai/lgenv/.vim/bundle/tabnine-vim/autoload/../python/ycm/diagnostic_interface.py", line 134, in UpdateMatches
    vimsupport.SwitchWindow( window )
  File "/data/mm64/jiuluncai/lgenv/.vim/bundle/tabnine-vim/autoload/../python/ycm/vimsupport.py", line 1250, in SwitchWindow
    vim.current.window = window
vim.error: Vim:E11: 在命令行窗口中无效；<CR> 执行，CTRL-C 退出
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/mm64/jiuluncai/lgenv/.vim/bundle/tabnine-vim/autoload/../python/ycm/youcompleteme.py", line 450, in UpdateMatches
    self.CurrentBuffer().UpdateMatches()
  File "/data/mm64/jiuluncai/lgenv/.vim/bundle/tabnine-vim/autoload/../python/ycm/buffer.py", line 88, in UpdateMatches
    self._diag_interface.UpdateMatches()
  File "/data/mm64/jiuluncai/lgenv/.vim/bundle/tabnine-vim/autoload/../python/ycm/diagnostic_interface.py", line 153, in UpdateMatches
    vimsupport.RemoveDiagnosticMatch( match )
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data/mm64/jiuluncai/lgenv/.vim/bundle/tabnine-vim/autoload/../python/ycm/vimsupport.py", line 1243, in CurrentWindow
    vim.current.window = current_window
vim.error: Vim:E11: 在命令行窗口中无效；<CR> 执行，CTRL-C 退出

vim version:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2020 17:34:40)

+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save

**Comment by chip** [comment]
I also get this error when typing `q:`

**Comment by kabeervohra** [comment]
I get this issue too, can this be looked at?
