### ISSUE TITLE
When selecting suggestion: Error detected while processing function <SNR>134_OnCompleteDone[1]..provider#python3#

### ISSUE THREAD

**Issue by MrcJkb** [codota/tabnine-vim#80]
- OS version:  Arch Linux
 - Editor version (Output of `vim --version`): NVIM v0.5.0-dev+1353-g0a653f7ab
 - Programming language: Java
 - TabNine extension version(Type `TabNine::version` in insert mode): 3.4.2

**Issue Details:**
When selecting a completion suggestion with the tabnine-plugin enabled, I get the following traceback:
```
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mrcjk/.config/nvim/pack/minpac/start/tabnine-vim/autoload/../python/ycm/youcompleteme.py", line 493, in OnCompleteDone
    completion_request.OnCompleteDone()
  File "/home/mrcjk/.config/nvim/pack/minpac/start/tabnine-vim/autoload/../python/ycm/client/completion_request.py", line 90, in OnCompleteDone
    action()
  File "/home/mrcjk/.config/nvim/pack/minpac/start/tabnine-vim/autoload/../python/ycm/client/completion_request.py", line 140, in _OnCompleteDone_FixIt
    completions = self._GetCompletionsUserMayHaveCompleted()
  File "/home/mrcjk/.config/nvim/pack/minpac/start/tabnine-vim/autoload/../python/ycm/client/completion_request.py", line 114, in _GetCompletionsUserMayHaveCompleted
    return [ completions[ int( completed_item[ 'user_data' ] ) ] ]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
```

gz#1117

**Comment by MrcJkb** [comment]
Update: It appears to happen mainly with language server and ultisnips suggestions.

**Comment by judewang** [comment]
I have this issue, too. Don't know is it better to use tabnine-vim rather than coc-tabnine? https://github.com/neoclide/coc-tabnine

**Comment by MrcJkb** [comment]
> I have this issue, too. Don't know is it better to use tabnine-vim rather than coc-tabnine? https://github.com/neoclide/coc-tabnine

I don't use coc, because it has issues with my preferred completion plugin nvim-compe.
