### ISSUE TITLE
YCM server error out

### ISSUE THREAD

**Issue by vnikk** [codota/tabnine-vim#88]
**please complete the following information:**	
 - OS version: MacOS Mojave
 - Editor version (Output of `vim --version`):
      VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 26 2020 06:16:12)
      macOS version
      Included patches: 1-539

 - Programming language: Python
 - TabNine extension version: 3.5.33
 
 **If the issue is related to TabNine failure, please provide log files:**	

Not related to TabNine directly.

**Issue Details:**
YCM is not able to start properly. Do I need to troubleshoot it with original YCM team?

:YcmDebugInfo
```
Printing YouCompleteMe debug information...
-- Client logfile: /var/folders/fw/hqrp814s6r5f54kxbx0hd38nvk2z2s/T/ycm_4j12hrbd.log
-- Server errored, no debug info from server
-- Server running at: http://127.0.0.1:52151
-- Server process ID: 65501
-- Server logfiles:
--   /var/folders/fw/hqrp814s6r5f54kxbx0hd38nvk2z2s/T/ycmd_52151_stdout_f2c2scx0.log
--   /var/folders/fw/hqrp814s6r5f54kxbx0hd38nvk2z2s/T/ycmd_52151_stderr_fiubn6vq.log
```

$ cat /var/folders/fw/hqrp814s6r5f54kxbx0hd38nvk2z2s/T/ycm_4j12hrbd.log # other logs are empty
```
2021-08-03 14:24:13,951 - ERROR - Unable to connect to server
Traceback (most recent call last):
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/packages/urllib3/connection.py", line 136, in _new_conn
    conn = connection.create_connection(
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/packages/urllib3/connectionpool.py", line 557, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/packages/urllib3/connection.py", line 145, in _new_conn
    raise NewConnectionError(
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x112df0580>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/adapters.py", line 366, in send
    resp = conn.urlopen(
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/packages/urllib3/connectionpool.py", line 608, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52151): Max retries exceeded with url: /ready (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x112df0580>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/.vim/bundle/tabnine-vim/autoload/../python/ycm/client/base_request.py", line 79, in HandleFuture
    return _JsonFromFuture( future )
  File "/Users/username/.vim/bundle/tabnine-vim/autoload/../python/ycm/client/base_request.py", line 239, in _JsonFromFuture
    response = future.result()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/username/.vim/bundle/tabnine-vim/autoload/../python/ycm/unsafe_thread_pool_executor.py", line 43, in run
    result = self.fn( *self.args, **self.kwargs )
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/username/.vim/bundle/tabnine-vim/third_party/ycmd/third_party/requests/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=52151): Max retries exceeded with url: /ready (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x112df0580>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

**Comment by maya-tabnine** [comment]
Hi! To figure out the cause, you need to locate your binary files and run the engine directly.
On Tabnine Hub, scroll down to the Engine file path, and find the Tabnine file path.
The path should be: 
/Users/{UserName}/.vim/bundle/tabnine-vim/binaries/{Binary_Version}/x86_64-apple-darwin/

Try to run the following command from the terminal using the right path:
`PATH_TO_ENGINE/TabNine.cmd --log_to_stderr`

Would you please collect the output to a file and share it with us?

**Comment by vnikk** [comment]
Hi maya-tabnine. Thanks for helping with this!
I can see these errors:
`Failed to remove private models from cache: No such file or directory (os error 2)`
Hard to say if this is relevant to server being down.

Also, 
`
Got new local client connection 127.0.0.1:59425`
Running `:YcmRestartServer` changes client port:
```
Got new local client connection 127.0.0.1:59444
```
(server port: 59440)
